# Generated by Django 4.2 on 2025-11-04 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0002_carritoitem'),
    ]

    operations = [
    ]
