# Generated by Django 4.2 on 2025-11-04 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0004_auto_20251103_2212'),
    ]

    operations = [
    ]
