# Generated by Django 4.2 on 2025-11-04 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0006_auto_20251103_2216'),
    ]

    operations = [
    ]
