# Generated by Django 4.2 on 2025-11-05 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0009_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='asunto',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='creado_en',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='correo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='mensaje',
            table='mensajes',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='principal_producto',
        ),
        migrations.DeleteModel(
            name='CarritoItem',
        ),
    ]
