# Generated by Django 4.2 on 2025-11-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0011_pedido_detallepedido'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='productos',
        ),
    ]
