# Generated by Django 4.2 on 2025-11-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0014_alter_pedido_total_alter_pedido_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
